services:
  nginx:
    image: lg-nginx
    build:
      context: ..
      dockerfile: backend/docker/nginx/Dockerfile
    ports: !override
      - "80:80"
    restart: unless-stopped
    volumes: !override []

  backend:
    image: lg-backend
    build:
      args:
        INSTALL_DEV: "false"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL:-${APP_URL}}
    restart: unless-stopped
    volumes: !override
      - app_storage:/var/www/html/storage

  worker:
    image: lg-backend
    build: !reset null
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      FRONTEND_URL: ${FRONTEND_URL:-${APP_URL}}
    restart: unless-stopped
    volumes: !override
      - app_storage:/var/www/html/storage

  mysql:
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  app_storage:
  mysql_data:
